# Exercise 6.1 - Sourcing Open Data

## Chocolate Bar Ratings - Cleaning and Consistency Checks

## -

### 1. Importing Libraries & Data

In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Create path
path = r'/Users/puneet/Desktop/Chocolate Bar Analysis 09-2025'

In [3]:
# Import Chocolate Bar Ratings CSV dataset
df_cbr = pd.read_csv(os.path.join(path,'02-Data','Original Data Files', 'flavors_of_cacao.csv'), index_col = False)

## -

### 2. Data Cleaning & Consistency Checks

In [4]:
# Check data head
df_cbr.head()

,Company \n(Maker-if known),Specific Bean Origin\nor Bar Name,REF,Review\nDate,Cocoa\nPercent,Company\nLocation,Rating,Bean\nType,Broad Bean\nOrigin
0,A. Morin,Agua Grande,1876,2016,63%,France,3.75,,Sao Tome
1,A. Morin,Kpime,1676,2015,70%,France,2.75,,Togo
2,A. Morin,Atsane,1676,2015,70%,France,3.00,,Togo
3,A. Morin,Akata,1680,2015,70%,France,3.50,,Togo
4,A. Morin,Quilla,1704,2015,70%,France,3.50,,Peru

In [5]:
df_cbr.columns

Index(['Company \n(Maker-if known)', 'Specific Bean Origin\nor Bar Name',
       'REF', 'Review\nDate', 'Cocoa\nPercent', 'Company\nLocation', 'Rating',
       'Bean\nType', 'Broad Bean\nOrigin'],
      dtype='object')

In [6]:
# Rename Columns
df_cbr = df_cbr.rename(columns = {
    'Company \n(Maker-if known)': 'Company',
    'Specific Bean Origin\nor Bar Name': 'Bar_Name',
    'REF': 'Reference_Number',
    'Review\nDate': 'Review_Date',
    'Cocoa\nPercent': 'Cocoa_Percentage',
    'Company\nLocation': 'Company_Location',
    'Bean\nType': 'Bean_Type',
    'Broad Bean\nOrigin': 'Bean_Origin'
})

In [7]:
# Check new column names
df_cbr.columns

Index(['Company \n(Maker-if known)', 'Bar_Name', 'Reference_Number',
       'Review_Date', 'Cocoa_Percentage', 'Company_Location', 'Rating',
       'Bean_Type', 'Bean_Origin'],
      dtype='object')

In [8]:
# Rename Columns (First column name didn't change)
df_cbr.columns = ['Company','Bar_Name', 'Reference_Number',
       'Review_Date', 'Cocoa_Percentage', 'Company_Location', 'Rating',
       'Bean_Type', 'Bean_Origin']

In [9]:
df_cbr.columns

Index(['Company', 'Bar_Name', 'Reference_Number', 'Review_Date',
       'Cocoa_Percentage', 'Company_Location', 'Rating', 'Bean_Type',
       'Bean_Origin'],
      dtype='object')

In [10]:
# Check new table
df_cbr.head()

,Company,Bar_Name,Reference_Number,Review_Date,Cocoa_Percentage,Company_Location,Rating,Bean_Type,Bean_Origin
0,A. Morin,Agua Grande,1876,2016,63%,France,3.75,,Sao Tome
1,A. Morin,Kpime,1676,2015,70%,France,2.75,,Togo
2,A. Morin,Atsane,1676,2015,70%,France,3.00,,Togo
3,A. Morin,Akata,1680,2015,70%,France,3.50,,Togo
4,A. Morin,Quilla,1704,2015,70%,France,3.50,,Peru

In [11]:
# Check data rows and columns
df_cbr.shape

(1795, 9)

- Dataset contains 1795 rows and 9 columns worht of data

In [12]:
# Check info on data columns
df_cbr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1795 non-null   object
 1   Bar_Name          1795 non-null   object
 2   Reference_Number  1795 non-null   int64
 3   Review_Date       1795 non-null   int64
 4   Cocoa_Percentage  1795 non-null   object
 5   Company_Location  1795 non-null   object
 6   Rating            1795 non-null   float64
 7   Bean_Type         1794 non-null   object
 8   Bean_Origin       1794 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 126.3+ KB

In [13]:
# Check data types for the columns
df_cbr.dtypes

Company              object
Bar_Name             object
Reference_Number      int64
Review_Date           int64
Cocoa_Percentage     object
Company_Location     object
Rating              float64
Bean_Type            object
Bean_Origin          object
dtype: object

In [14]:
# Change 'Cocoa_Percerntage' column to float, instead of string as it displays percentages. Remove "%" symbol
df_cbr['Cocoa_Percentage'] = df_cbr['Cocoa_Percentage'].str.rstrip('%').astype(float)

In [15]:
# Show new Cocoa_Percentage info
df_cbr['Cocoa_Percentage'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1795 entries, 0 to 1794
Series name: Cocoa_Percentage
Non-Null Count  Dtype
--------------  -----
1795 non-null   float64
dtypes: float64(1)
memory usage: 14.2 KB

In [16]:
df_cbr.head(2)

,Company,Bar_Name,Reference_Number,Review_Date,Cocoa_Percentage,Company_Location,Rating,Bean_Type,Bean_Origin
0,A. Morin,Agua Grande,1876,2016,63.0,France,3.75,,Sao Tome
1,A. Morin,Kpime,1676,2015,70.0,France,2.75,,Togo

In [17]:
#Check for Mixed-type column
for col in df_cbr.columns.tolist():
  weird = (df_cbr[[col]].map(type) != df_cbr[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_cbr[weird]) > 0:
    print (col)

Bean_Type
Bean_Origin

In [18]:
#Change Bean_Type and Bean_Origin to Strings (No numeric values for these columns)
df_cbr['Bean_Type'] = df_cbr['Bean_Type'].astype(str)
df_cbr['Bean_Origin'] = df_cbr['Bean_Origin'].astype(str)

#Check new columns
df_cbr[['Bean_Type','Bean_Origin']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Bean_Type    1795 non-null   object
 1   Bean_Origin  1795 non-null   object
dtypes: object(2)
memory usage: 28.2+ KB

In [19]:
#Check for Mixed-type column (After cleaning)
for col in df_cbr.columns.tolist():
  weird = (df_cbr[[col]].map(type) != df_cbr[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_cbr[weird]) > 0:
    print (col)

- No mixed-type columns

In [20]:
#Describe Numerical Data
df_cbr.describe()

       Reference_Number  Review_Date  Cocoa_Percentage       Rating
count       1795.000000  1795.000000       1795.000000  1795.000000
mean        1035.904735  2012.325348         71.698329     3.185933
std          552.886365     2.927210          6.323118     0.478062
min            5.000000  2006.000000         42.000000     1.000000
25%          576.000000  2010.000000         70.000000     2.875000
50%         1069.000000  2013.000000         70.000000     3.250000
75%         1502.000000  2015.000000         75.000000     3.500000
max         1952.000000  2017.000000        100.000000     5.000000

- Descriptive Statistics Look Clean

In [21]:
#Check values for 'Bean_Type' (Missing values)
df_cbr['Bean_Type'].value_counts()

Bean_Type
                            887
Trinitario                  419
Criollo                     153
Forastero                    87
Forastero (Nacional)         52
Blend                        41
Criollo, Trinitario          39
Forastero (Arriba)           37
Criollo (Porcelana)          10
Trinitario, Criollo           9
Forastero (Parazinho)         8
Forastero (Arriba) ASS        6
Beniano                       3
Matina                        3
EET                           3
Nacional (Arriba)             3
Criollo, Forastero            2
Amazon, ICS                   2
Trinitario, Forastero         2
Amazon mix                    2
Forastero (Catongo)           2
Nacional                      2
Trinitario (85% Criollo)      2
Criollo (Amarru)              2
Criollo (Ocumare 61)          2
Criollo, +                    1
Forastero (Arriba) ASSS       1
Trinitario, TCGA              1
Trinitario (Amelonado)        1
Trinitario, Nacional          1
nan                           1
Forastero (Amelonado)         1
Forastero, Trinitario         1
Criollo (Ocumare 77)          1
Amazon                        1
Forastero(Arriba, CCN)        1
Criollo (Ocumare 67)          1
CCN51                         1
Trinitario (Scavina)          1
Blend-Forastero,Criollo       1
Criollo (Ocumare)             1
Criollo (Wild)                1
Name: count, dtype: int64

In [22]:
#Check Null values in Bean_Type column
df_cbr['Bean_Type'].isnull().sum()

np.int64(0)

- *No nulls counted, but blank values showing in table (887 Counts)*

In [23]:
#List Bean Type values to see "Nulls"
list(df_cbr['Bean_Type'])

['\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 'Criollo',
 'Criollo',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Criollo',
 'Trinitario',
 'Criollo',
 'Forastero',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Forastero (Nacional)',
 'Criollo, Trinitario',
 'Trinitario',
 'Forastero',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Criollo',
 'Forastero',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo (Porcelana)',
 'Blend',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario (85% Criollo)',
 'Trinitario (85% Criollo)',
 'Trinitario',
 'Blend',
 'Blend',
 'Blend',
 'Forastero (Catongo)',
 'Forastero (Parazinho)',
 'Forastero (Parazinho)',
 'Forastero (Parazinho)',
 'Forastero (Parazinho)',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 'Forastero (Nacional)',
 '\xa0',
 'Trinitario',
 'Criollo, Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Criollo, Trinitario',
 'Trinitario',
 '\xa0',
 'Criollo, Trinitario',
 'Criollo',
 'Trinitario',
 'Forastero',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Forastero (Arriba)',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Blend',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo, Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo',
 'Criollo',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Criollo (Porcelana)',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Forastero',
 '\xa0',
 'Blend',
 '\xa0',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Forastero',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Forastero (Nacional)',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Criollo',
 'Criollo',
 'Criollo',
 'Criollo (Porcelana)',
 'Forastero (Arriba)',
 'Trinitario',
 '\xa0',
 'Criollo',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Trinitario',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Forastero',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Blend',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario, Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Criollo',
 'Criollo',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Blend',
 '\xa0',
 '\xa0',
 'Forastero',
 'Trinitario',
 'Criollo',
 '\xa0',
 'Criollo',
 '\xa0',
 'Trinitario',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero',
 'Forastero',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'CCN51',
 'Trinitario',
 'Trinitario',
 'Criollo, Trinitario',
 '\xa0',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo',
 '\xa0',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 'Forastero (Arriba)',
 'Forastero (Arriba)',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo',
 'Criollo',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo (Ocumare)',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Forastero',
 'Criollo',
 'Forastero (Nacional)',
 'Trinitario',
 'Forastero (Nacional)',
 'Forastero (Arriba)',
 'Criollo',
 'Criollo',
 'Criollo',
 'Criollo',
 '\xa0',
 'Criollo',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Criollo',
 'Forastero (Arriba)',
 'Trinitario',
 'Blend',
 'Trinitario',
 'Trinitario',
 'Criollo',
 'Criollo',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 'Criollo',
 'Trinitario',
 'Forastero',
 'Forastero',
 'Forastero',
 'Forastero',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Criollo',
 'Forastero (Nacional)',
 '\xa0',
 'Trinitario',
 'Forastero (Nacional)',
 'Forastero',
 '\xa0',
 'Forastero',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Nacional',
 'Trinitario',
 'Trinitario',
 'Criollo (Ocumare 61)',
 'Criollo',
 'Criollo',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 'Criollo',
 'Criollo (Porcelana)',
 'Trinitario',
 '\xa0',
 'Forastero',
 'Trinitario',
 'Forastero',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Forastero',
 'Forastero (Nacional)',
 'Forastero (Nacional)',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 'Criollo',
 'Criollo',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Criollo, Trinitario',
 '\xa0',
 'Forastero',
 '\xa0',
 '\xa0',
 'Criollo (Ocumare 77)',
 'Criollo',
 '\xa0',
 'Criollo',
 'Criollo',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Blend',
 'Blend',
 'Criollo (Porcelana)',
 'Criollo (Ocumare 61)',
 'Trinitario',
 'Trinitario',
 'Criollo',
 'Criollo',
 'Forastero (Arriba)',
 'Criollo (Ocumare 67)',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 'Criollo',
 'Criollo',
 'Criollo',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Forastero (Nacional)',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Criollo',
 'Criollo',
 'Criollo',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 'Forastero',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Criollo',
 '\xa0',
 'Criollo',
 '\xa0',
 'Trinitario',
 'Criollo (Porcelana)',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Trinitario, Criollo',
 'Criollo',
 'Criollo',
 'Forastero (Arriba)',
 'Criollo (Wild)',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Forastero',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 '\xa0',
 'Forastero (Nacional)',
 'Forastero (Nacional)',
 'Forastero (Nacional)',
 'Forastero (Nacional)',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Forastero',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 '\xa0',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 'Beniano',
 'Amazon mix',
 'Trinitario',
 'Forastero (Nacional)',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Blend',
 'Trinitario',
 'Forastero',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Trinitario, Forastero',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Forastero (Arriba) ASS',
 'Forastero',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Blend',
 '\xa0',
 '\xa0',
 '\xa0',
 'Blend',
 'Trinitario',
 'Trinitario, Criollo',
 'Criollo, +',
 'Forastero (Arriba)',
 'Blend',
 'Blend',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero (Arriba)',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Amazon',
 'Amazon mix',
 'Amazon, ICS',
 'Beniano',
 'EET',
 '\xa0',
 '\xa0',
 'EET',
 'EET',
 'Amazon, ICS',
 'Beniano',
 'Forastero',
 'Criollo',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo',
 'Forastero (Arriba) ASS',
 'Forastero (Arriba) ASS',
 'Forastero (Arriba) ASS',
 'Forastero (Arriba) ASS',
 'Forastero (Arriba) ASS',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Forastero (Nacional)',
 'Trinitario',
 'Forastero (Nacional)',
 '\xa0',
 'Forastero (Nacional)',
 '\xa0',
 'Trinitario, Criollo',
 'Forastero (Nacional)',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Forastero',
 '\xa0',
 'Forastero',
 'Trinitario',
 'Criollo, Trinitario',
 'Criollo, Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 'Trinitario, Criollo',
 'Forastero',
 'Trinitario',
 'Criollo',
 '\xa0',
 'Criollo',
 'Criollo',
 'Criollo',
 'Criollo',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 '\xa0',
 'Forastero',
 'Forastero',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 'Trinitario, Criollo',
 'Trinitario, Criollo',
 'Criollo',
 'Trinitario, Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Forastero',
 'Criollo (Porcelana)',
 '\xa0',
 '\xa0',
 'Blend',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 'Forastero (Catongo)',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 'Forastero (Nacional)',
 'Criollo',
 'Trinitario',
 'Criollo',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 'Criollo',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 'Trinitario',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 ...]

- We see the value '\xa0' showing up as nulls

In [24]:
#Replace values with 'Unknown'
df_cbr['Bean_Type'] = df_cbr['Bean_Type'].replace('\xa0','Unknown')

In [25]:
#Check 'Bean_Type' Values again (After replacement above)
df_cbr['Bean_Type'].value_counts()

Bean_Type
Unknown                     887
Trinitario                  419
Criollo                     153
Forastero                    87
Forastero (Nacional)         52
Blend                        41
Criollo, Trinitario          39
Forastero (Arriba)           37
Criollo (Porcelana)          10
Trinitario, Criollo           9
Forastero (Parazinho)         8
Forastero (Arriba) ASS        6
Beniano                       3
Matina                        3
EET                           3
Nacional (Arriba)             3
Criollo, Forastero            2
Amazon, ICS                   2
Trinitario, Forastero         2
Amazon mix                    2
Forastero (Catongo)           2
Nacional                      2
Trinitario (85% Criollo)      2
Criollo (Amarru)              2
Criollo (Ocumare 61)          2
Criollo, +                    1
Forastero (Arriba) ASSS       1
Trinitario, TCGA              1
Trinitario (Amelonado)        1
Trinitario, Nacional          1
nan                           1
Forastero (Amelonado)         1
Forastero, Trinitario         1
Criollo (Ocumare 77)          1
Amazon                        1
Forastero(Arriba, CCN)        1
Criollo (Ocumare 67)          1
CCN51                         1
Trinitario (Scavina)          1
Blend-Forastero,Criollo       1
Criollo (Ocumare)             1
Criollo (Wild)                1
Name: count, dtype: int64

#### Null values have been changed to 'Unknown' in Bean Type Column

In [26]:
#Check 'Bean_Origin' Values
df_cbr['Bean_Origin'].value_counts().head(50)

Bean_Origin
Venezuela                 214
Ecuador                   193
Peru                      165
Madagascar                145
Dominican Republic        141
                           73
Nicaragua                  60
Brazil                     58
Bolivia                    57
Belize                     49
Papua New Guinea           42
Colombia                   40
Vietnam                    38
Costa Rica                 38
Tanzania                   34
Trinidad                   33
Ghana                      33
Mexico                     30
Guatemala                  28
Hawaii                     28
Domincan Republic          25
Jamaica                    20
Grenada                    19
Indonesia                  16
Honduras                   15
Cuba                       11
Sao Tome                   10
Congo                      10
Haiti                       9
Carribean                   8
Uganda                      8
St. Lucia                   8
Fiji                        8
Panama                      7
Sao Tome & Principe         7
Vanuatu                     7
West Africa                 6
Philippines                 5
Ivory Coast                 5
Puerto Rico                 4
Central and S. America      4
India                       4
Solomon Islands             4
Liberia                     3
Colombia, Ecuador           3
Togo                        3
Malaysia                    3
Australia                   3
South America               3
El Salvador                 2
Name: count, dtype: int64

- 73 Missing values showing in 'Bean_Origin'

In [27]:
#List Bean Origin values
list(df_cbr['Bean_Origin'])

['Sao Tome',
 'Togo',
 'Togo',
 'Togo',
 'Peru',
 'Venezuela',
 'Cuba',
 'Venezuela',
 'Venezuela',
 'Peru',
 'Panama',
 'Madagascar',
 'Brazil',
 'Ecuador',
 'Colombia',
 'Burma',
 'Papua New Guinea',
 'Venezuela',
 'Peru',
 'Peru',
 'Peru',
 'Bolivia',
 'Peru',
 'Peru',
 'Peru',
 'Fiji',
 'Fiji',
 'Fiji',
 'Fiji',
 'Ecuador',
 'Ecuador',
 'Mexico',
 'Indonesia',
 'Madagascar',
 'Brazil',
 'Trinidad',
 'Vietnam',
 'Madagascar',
 'Venezuela',
 'Peru',
 'Ecuador',
 'Nicaragua',
 'Vietnam',
 'Tanzania',
 'Nicaragua',
 'Peru',
 'Bolivia',
 'Peru',
 'Ecuador',
 'Venezuela',
 'Dominican Republic',
 'Bolivia',
 'Bolivia',
 'Peru',
 'Papua New Guinea',
 'Dominican Republic',
 'Ecuador',
 'Venezuela',
 'Venezuela',
 'Indonesia',
 'Madagascar',
 'Venezuela',
 'Venezuela',
 'Ghana',
 'Ecuador',
 'Ecuador',
 'Ghana',
 'Peru',
 'Peru',
 'Belize',
 'Madagascar',
 'Dominican Republic',
 'Papua New Guinea',
 'Venezuela',
 'Peru',
 'Peru',
 'Venezuela',
 '\xa0',
 'Venezuela',
 'Ecuador',
 'Jamaica',
 'Grenada',
 'Venezuela',
 'Madagascar',
 'Trinidad',
 '\xa0',
 '\xa0',
 '\xa0',
 'Brazil',
 'Brazil',
 'Brazil',
 'Brazil',
 'Brazil',
 'Dominican Republic',
 'Bolivia',
 'Madagascar',
 'Mexico',
 'Ecuador',
 'Venezuela',
 'Trinidad',
 'Tanzania',
 'Vietnam',
 'Ecuador',
 'Ecuador',
 'Guatemala',
 'Nicaragua',
 'Honduras',
 'Costa Rica',
 'Peru',
 'Dominican Republic',
 'Fiji',
 'Vietnam',
 'Brazil',
 'Peru',
 'Ecuador',
 'Domincan Republic',
 'Belize',
 'Nicaragua',
 'Brazil',
 'Guatemala',
 'Ecuador',
 'Trinidad',
 'Colombia',
 'Haiti',
 'Panama',
 'Venezuela',
 'Jamaica',
 'Costa Rica',
 'Vietnam',
 'Indonesia',
 'Venezuela',
 'Indonesia',
 'Brazil',
 'Madagascar',
 'Peru',
 'Dominican Republic',
 'Congo',
 'Colombia',
 'Tanzania',
 'Tanzania',
 'Honduras',
 'Philippines',
 'Mexico',
 'Ecuador',
 '\xa0',
 'Papua New Guinea',
 'Madagascar',
 'Brazil',
 '\xa0',
 'Peru',
 'Peru',
 'Brazil',
 'Peru',
 'Dominican Republic',
 'Mexico',
 'Madagascar',
 'Costa Rica',
 'Domincan Republic',
 'Brazil',
 'Ecuador',
 'Malaysia',
 'Malaysia',
 'Brazil',
 'Domincan Republic',
 'Ecuador',
 'Ecuador',
 'Costa Rica',
 'Papua New Guinea',
 'Peru',
 'Ecuador',
 'Tanzania',
 'Bolivia',
 'Domincan Republic',
 'Belize',
 'Belize',
 'Belize',
 'Cuba',
 'Venezuela',
 'Venezuela',
 'Ecuador',
 'Indonesia',
 'Madagascar',
 '\xa0',
 'Madagascar',
 'Venezuela',
 'Venezuela',
 'Ecuador',
 'Venezuela',
 'Venezuela',
 'Indonesia',
 'Venezuela',
 'Nicaragua',
 'Costa Rica',
 'Costa Rica',
 'Belize',
 'Ghana',
 'Indonesia',
 'Dominican Rep., Bali',
 'Indonesia',
 'Madagascar',
 'Venezuela',
 'Dominican Republic',
 'Dominican Republic',
 'Madagascar',
 'Madagascar',
 'Madagascar',
 'Panama',
 'Dominican Republic',
 'Ghana',
 'Dominican Republic',
 'Venezuela',
 'Nicaragua',
 'Jamaica',
 'Congo',
 '\xa0',
 'Madagascar',
 'Guatemala',
 'Tanzania',
 'Dominican Republic',
 'Guatemala',
 'Madagascar',
 'Mexico',
 'Brazil',
 'Dominican Republic',
 'Venez,Africa,Brasil,Peru,Mex',
 'Brazil',
 'Gabon',
 'Cuba',
 'Peru',
 'Peru',
 'Brazil',
 'Haiti',
 'Madagascar',
 'Brazil',
 'Jamaica',
 'Ivory Coast',
 'Peru',
 'Mexico',
 'Mexico',
 'Venezuela',
 'Ecuador',
 'Carribean',
 'Venezuela',
 'Venezuela',
 'Madagascar',
 '\xa0',
 'Sri Lanka',
 'Venezuela',
 'Ecuador',
 'Ecuador',
 'Belize',
 'Dominican Republic',
 'Venezuela',
 'Nicaragua',
 'Dominican Republic',
 'Belize',
 'Venezuela',
 'Dominican Republic',
 'Ecuador',
 'Ghana',
 'Venezuela',
 'Dominican Republic',
 'Dominican Republic',
 'Guatemala',
 'Madagascar',
 'Belize',
 'Madagascar',
 'Jamaica',
 'Madagascar',
 'Dominican Republic',
 'Ecuador',
 'Trinidad',
 'Ecuador',
 'Dominican Republic',
 'Trinidad',
 'Ecuador',
 'Belize',
 '\xa0',
 'Ecuador',
 'Puerto Rico',
 'Peru',
 'Dominican Republic',
 'Dominican Republic',
 'Venezuela',
 'Haiti',
 'Dominican Republic',
 'Tanzania',
 'Venezuela',
 'Mexico',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Colombia',
 'Colombia',
 'Colombia',
 'Colombia',
 'Colombia',
 'Colombia',
 'Colombia',
 'Honduras',
 'Dominican Republic',
 'Dominican Republic',
 'Dominican Republic',
 'Dominican Republic',
 'Congo',
 'Madagascar',
 'Ecuador',
 'Papua New Guinea',
 'Grenada',
 'Venezuela',
 'Venezuela',
 'Mexico',
 'Mexico',
 'Madagascar',
 'Peru',
 'Vietnam',
 'Peru',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Grenada',
 'Ecuador',
 'Cuba',
 'Dominican Republic',
 '\xa0',
 'Ecuador',
 'Venezuela',
 'Sao Tome',
 'Trinidad',
 'Venezuela',
 'Tanzania',
 'Venezuela',
 'Bolivia',
 'Brazil',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Papua New Guinea',
 'Papua New Guinea',
 'Guatemala',
 'Costa Rica',
 'Costa Rica',
 'Costa Rica',
 'Costa Rica',
 'Colombia',
 'Colombia',
 'Colombia',
 'Colombia',
 'Colombia',
 'Belize',
 'Honduras',
 'Domincan Republic',
 'Venezuela',
 'Colombia',
 'Colombia',
 'Dominican Republic',
 'Bolivia',
 'Dominican Republic',
 'Peru',
 'Venezuela',
 'Nicaragua',
 'Peru',
 'Venezuela',
 'Ecuador',
 'Peru',
 'Venezuela',
 'Bolivia',
 'Ecuador',
 'Uganda',
 'Belize',
 'Ecuador',
 'Ecuador',
 'Costa Rica',
 '\xa0',
 'Ecuador',
 'Belize',
 'Belize',
 'Vietnam',
 'Malaysia',
 'Peru',
 'Peru',
 'Dominican Republic',
 'Madagascar',
 'Venezuela',
 'Peru',
 '\xa0',
 'Bolivia',
 'Uganda',
 'Dominican Republic',
 'Dominican Republic',
 'Venezuela',
 'Ecuador',
 'Nicaragua',
 'Peru',
 'Dominican Republic',
 'Congo',
 'Peru',
 'Peru',
 'Venezuela',
 'Peru',
 'Ecuador',
 'Peru',
 'Madagascar',
 'Mexico',
 'Venezuela',
 'Mexico',
 'Mexico',
 'Madagascar',
 '\xa0',
 '\xa0',
 'Venezuela',
 'Ecuador',
 'Grenada',
 '\xa0',
 'Mexico',
 'Mexico',
 'Venezuela',
 'Mexico',
 'Brazil',
 'Brazil',
 'Venezuela',
 'Martinique',
 'Mexico',
 'Peru',
 'Venezuela',
 'Venezuela',
 'Sao Tome & Principe',
 'Sao Tome & Principe',
 'Sao Tome & Principe',
 'Sao Tome & Principe',
 'Ecuador',
 'Madagascar',
 'Venezuela',
 'Venezuela',
 'Bolivia',
 'Venezuela',
 'Ecuador',
 'Ecuador',
 'Vietnam',
 'Ecuador',
 'Ghana',
 'Ecuador',
 'Sao Tome & Principe',
 'Madagascar',
 'Grenada',
 'Venezuela',
 'Ecuador',
 'Trinidad',
 'Jamaica',
 'Venezuela',
 'Peru',
 'Peru',
 'Venezuela',
 'Venezuela',
 'Mexico',
 'Venezuela',
 'Madagascar',
 '\xa0',
 'Papua New Guinea',
 'Vanuatu',
 'Tanzania',
 'Brazil',
 'Fiji',
 'Vanuatu',
 'Papua New Guinea',
 'Ecuador',
 'Ecuador',
 'Australia',
 'Australia',
 'Dominican Republic',
 'Trinidad',
 'Ecuador',
 'Grenada',
 'Nicaragua',
 '\xa0',
 'Belize',
 'Belize',
 'Ecuador',
 'Liberia',
 'Dominican Republic',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Papua New Guinea',
 'Costa Rica',
 'Colombia',
 'Dominican Republic',
 'Dominican Republic',
 'Madagascar',
 'Tanzania',
 'Guatemala',
 'Venezuela',
 'Guatemala',
 'Madagascar',
 'Guatemala',
 'Guatemala',
 'Guatemala',
 'Guatemala',
 'Guatemala',
 'Venezuela',
 'Vietnam',
 'Ecuador, Costa Rica',
 'Bolivia',
 'Madagascar',
 'Venezuela',
 'Tanzania',
 'Ecuador',
 'Ghana',
 'Dominican Republic',
 'Venezuela',
 'West Africa',
 'Brazil',
 'Brazil',
 'Uganda',
 'Madagascar',
 'Madagascar',
 'Costa Rica',
 'Ecuador',
 'Ghana',
 'Papua New Guinea',
 'Peru',
 'Papua New Guinea',
 'Venezuela',
 'Tanzania',
 'Bolivia',
 'Costa Rica',
 'Dominican Republic',
 'Guatemala',
 'Vietnam',
 'Bolivia',
 'Dominican Republic',
 'Ecuador',
 'Ecuador',
 'Bolivia',
 'Belize',
 'Madagascar',
 'Madagascar',
 'Venezuela',
 'Dominican Republic',
 'Ecuador',
 'Venezuela',
 'Panama',
 'Venezuela',
 'Nicaragua',
 'Hawaii',
 'West Africa',
 '\xa0',
 'Ecuador',
 'Venezuela',
 'Venezuela',
 'Tanzania',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Colombia',
 '\xa0',
 '\xa0',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Madagascar',
 'Madagascar',
 'Indonesia',
 'Ecuador',
 'Venezuela',
 'Venezuela',
 'Peru',
 'Venezuela',
 'Grenada',
 'Venezuela',
 'Colombia',
 'Madagascar',
 'Guatemala',
 'Nicaragua',
 'Nicaragua',
 'Venezuela',
 'Honduras',
 'Dominican Republic',
 'Panama',
 'Nicaragua',
 'Venezuela',
 'Panama',
 'Ecuador',
 'Ecuador',
 'Peru',
 'Dominican Republic',
 'Madagascar',
 'Peru',
 'Venezuela',
 'Domincan Republic',
 'Venezuela',
 'Ecuador',
 'Peru',
 'Madagascar',
 'Dominican Republic',
 'Colombia',
 'Colombia',
 'Peru',
 'Venezuela',
 'Bolivia',
 'Bolivia',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'St. Lucia',
 'St. Lucia',
 'Venezuela',
 'Peru',
 'Honduras',
 'Sao Tome & Principe',
 'Vietnam',
 'Vietnam',
 'Vietnam',
 'Venezuela',
 'Costa Rica',
 'Venezuela',
 'Cost Rica, Ven',
 'Venezuela',
 'Peru, Madagascar',
 'Trinidad',
 'Venezuela',
 '\xa0',
 'Venezuela, Trinidad',
 'Belize',
 'Ecuador',
 'Dominican Republic',
 'Brazil',
 'Jamaica',
 'Venezuela',
 'Belize',
 'Grenada',
 '\xa0',
 'Dominican Republic',
 'Madagascar',
 'Venezuela',
 'Ecuador',
 'Bolivia',
 'Puerto Rico',
 'Dominican Republic',
 'Dominican Republic',
 'Dominican Republic',
 'Peru',
 'Domincan Republic',
 'Domincan Republic',
 'Madagascar',
 'Ecuador',
 'Tanzania',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Costa Rica',
 'Peru',
 'Vietnam',
 'Ghana',
 'Madagascar',
 'Peru',
 'Guatemala',
 'Costa Rica',
 'Nicaragua',
 'Peru',
 'Peru',
 'Peru',
 'Peru',
 'Peru',
 'Dominican Republic',
 'Peru',
 'Peru',
 'Peru',
 'Peru',
 'Dominican Republic',
 'Dominican Republic',
 'Peru',
 'Peru',
 'Papua New Guinea',
 'Papua New Guinea',
 'Madagascar',
 'Papua New Guinea',
 'Papua New Guinea',
 'Ghana',
 'Jamaica',
 'Dominican Republic',
 'Jamaica',
 'Madagascar',
 'Dominican Republic',
 'Madagascar',
 'Venezuela',
 'Venezuela',
 'Jamaica',
 'Jamaica',
 'Jamaica',
 'Venezuela',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Honduras',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Nicaragua',
 'Bolivia',
 'Costa Rica',
 'Trinidad',
 'Peru',
 'Dominican Republic',
 'Ecuador',
 'Peru',
 'Costa Rica',
 'Costa Rica',
 'Hawaii',
 'Madagascar',
 'Ghana',
 'Domincan Republic',
 'Domincan Republic',
 'Madagascar',
 'Belize',
 'Brazil',
 'Mexico',
 'Nicaragua',
 'Guatemala',
 'Vietnam',
 '\xa0',
 'Madagascar',
 'Grenada',
 'Grenada',
 'Grenada',
 'Ecuador',
 'Ghana',
 'Trinidad, Tobago',
 'Venezuela',
 'Ven, Trinidad, Ecuador',
 '\xa0',
 'Haiti',
 'Nicaragua',
 'Jamaica',
 'Ecuador',
 '\xa0',
 '\xa0',
 '\xa0',
 'Trinidad',
 'Hawaii',
 '\xa0',
 '\xa0',
 'Peru',
 '\xa0',
 'Venezuela',
 '\xa0',
 'Colombia',
 'Venezuela',
 'Madagascar',
 'Ecuador',
 '\xa0',
 '\xa0',
 'Papua New Guinea',
 '\xa0',
 'Dominican Republic',
 '\xa0',
 '\xa0',
 '\xa0',
 '\xa0',
 'Hawaii',
 '\xa0',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'South America, Africa',
 'Brazil',
 'Brazil',
 'Brazil',
 'Brazil',
 'Peru',
 'Belize',
 'Costa Rica',
 'Bolivia',
 'Bolivia',
 'Ecuador',
 'Hawaii',
 'Hawaii',
 'Ecuador',
 'Ecuador',
 'Bolivia',
 'Bolivia',
 'Uganda',
 'Venezuela',
 'Tanzania',
 'Madagascar',
 'Venezuela',
 'Ecuador',
 'Peru',
 'Madagascar',
 'Venezuela',
 'Domincan Republic',
 'Peru',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Peru',
 'Ecuador',
 'Madagascar',
 'Trinidad',
 'Venezuela',
 'Ivory Coast',
 'Dominican Republic',
 'Peru',
 'Dominican Republic',
 'Ecuador',
 'St. Lucia',
 'St. Lucia',
 'St. Lucia',
 'Trinidad',
 'Vietnam',
 'Ecuador',
 'Madagascar',
 'Ecuador',
 'Peru',
 'Ecuador',
 'Dominican Republic',
 'Madagascar',
 'Ecuador',
 'St. Lucia',
 'St. Lucia',
 'Ecuador',
 'Dominican Republic',
 'Venezuela',
 'St. Lucia',
 'Uganda',
 'Tanzania',
 'Sao Tome',
 'Vietnam',
 'Bolivia',
 'Bolivia',
 'Nicaragua',
 'Dominican Republic',
 'Dominican Republic',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'Venezuela',
 'India',
 'Dominican Republic',
 'Dominican Republic',
 'Honduras',
 'Peru',
 'Peru',
 'Madagascar',
 'Peru',
 'Belize',
 'Dominican Republic',
 'Belize',
 'Dominican Republic',
 'Ghana',
 'Madagascar',
 'Belize',
 'Madagascar',
 'Peru',
 'Dominican Republic',
 'Dominican Republic',
 'Dominican Republic',
 'Dominican Republic',
 'Peru',
 'Vanuatu',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 'Ecuador',
 '\xa0',
 'Ecuador',
 'Dominican Republic',
 'Mexico',
 'Dominican Republic',
 'Peru',
 'Venezuela',
 'Belize',
 'Madagascar',
 'Belize',
 'Dominican Republic',
 'Dominican Republic',
 'Haiti',
 'Peru',
 'Ecuador',
 'Brazil',
 'Uganda',
 'Dominican Republic',
 'Ecuador',
 'Madagascar',
 'Peru',
 'Brazil',
 'Venezuela',
 'Ecuador',
 'Grenada',
 'Dominican Republic',
 'Venezuela',
 'Madagascar',
 'Bolivia',
 'Peru',
 'Peru',
 'Peru',
 'Belize',
 'Africa, Carribean, C. Am.',
 'Tobago',
 'Ecuador',
 'Dominican Republic',
 'Grenada',
 'Ghana',
 'Venezuela',
 '\xa0',
 '\xa0',
 'Ven., Indonesia, Ecuad.',
 'Peru',
 'Ecuador',
 'Madagascar',
 'Vietnam',
 'Cuba',
 'Peru',
 'Ivory Coast',
 'Sao Tome',
 'Brazil',
 'Vietnam',
 'Cuba',
 'Trinidad-Tobago',
 'Brazil',
 'Tanzania',
 'Nicaragua',
 'Venezuela',
 'Venezuela',
 'Peru, Ecuador, Venezuela',
 'Honduras',
 'Belize',
 'Liberia',
 'Bolivia',
 'Trinidad',
 'Costa Rica',
 'Domincan Republic',
 'Tanzania',
 'Peru',
 'Madagascar',
 'Madagascar',
 'Peru',
 'Bolivia',
 'Peru',
 'Venezuela, Dom. Rep.',
 'Dominican Republic',
 'Bolivia',
 '\xa0',
 'Puerto Rico',
 'Hawaii',
 'Hawaii',
 'Hawaii',
 'Hawaii',
 'Hawaii',
 'Hawaii',
 'Nicaragua',
 'Colombia, Ecuador',
 'Colombia, Ecuador',
 'Colombia, Ecuador',
 'Colombia',
 'Peru',
 'Peru',
 'Madagascar',
 'Madagascar',
 'Madagascar',
 'Madagascar',
 'Solomon Islands',
 'Puerto Rico',
 'Brazil',
 'Hawaii',
 'Mexico',
 'Hawaii',
 ...]

- Replace same "Null" values in Bean_Origin that show \xa0'

In [28]:
#Replace Null Bean_Origin values with 'Unknown'
df_cbr['Bean_Origin'] = df_cbr['Bean_Origin'].replace('\xa0','Unknown')

In [29]:
#Check 'Bean_Origin' Values (After Cleaning)
df_cbr['Bean_Origin'].value_counts().head(10)

Bean_Origin
Venezuela             214
Ecuador               193
Peru                  165
Madagascar            145
Dominican Republic    141
Unknown                73
Nicaragua              60
Brazil                 58
Bolivia                57
Belize                 49
Name: count, dtype: int64

#### Null Values have been changed to 'Unknown' in Bean Origin Column

In [30]:
#Create new dataframe to check for duplicates
df_cbr_dups = df_cbr[df_cbr.duplicated()]

In [31]:
#Check duplicates table
df_cbr_dups

Empty DataFrame
Columns: [Company, Bar_Name, Reference_Number, Review_Date, Cocoa_Percentage, Company_Location, Rating, Bean_Type, Bean_Origin]
Index: []

- No duplicates in data

#### -

- Perform last data checks after cleaning

In [32]:
df_cbr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1795 non-null   object
 1   Bar_Name          1795 non-null   object
 2   Reference_Number  1795 non-null   int64
 3   Review_Date       1795 non-null   int64
 4   Cocoa_Percentage  1795 non-null   float64
 5   Company_Location  1795 non-null   object
 6   Rating            1795 non-null   float64
 7   Bean_Type         1795 non-null   object
 8   Bean_Origin       1795 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 126.3+ KB

In [33]:
df_cbr.shape

(1795, 9)

In [34]:
df_cbr.isnull().sum()

Company             0
Bar_Name            0
Reference_Number    0
Review_Date         0
Cocoa_Percentage    0
Company_Location    0
Rating              0
Bean_Type           0
Bean_Origin         0
dtype: int64

In [35]:
df_cbr.dtypes

Company              object
Bar_Name             object
Reference_Number      int64
Review_Date           int64
Cocoa_Percentage    float64
Company_Location     object
Rating              float64
Bean_Type            object
Bean_Origin          object
dtype: object

In [36]:
df_cbr.head(15)

,Company,Bar_Name,Reference_Number,Review_Date,Cocoa_Percentage,Company_Location,Rating,Bean_Type,Bean_Origin
0,A. Morin,Agua Grande,1876,2016,63.0,France,3.75,Unknown,Sao Tome
1,A. Morin,Kpime,1676,2015,70.0,France,2.75,Unknown,Togo
2,A. Morin,Atsane,1676,2015,70.0,France,3.00,Unknown,Togo
3,A. Morin,Akata,1680,2015,70.0,France,3.50,Unknown,Togo
4,A. Morin,Quilla,1704,2015,70.0,France,3.50,Unknown,Peru
5,A. Morin,Carenero,1315,2014,70.0,France,2.75,Criollo,Venezuela
6,A. Morin,Cuba,1315,2014,70.0,France,3.50,Unknown,Cuba
7,A. Morin,Sur del Lago,1315,2014,70.0,France,3.50,Criollo,Venezuela
8,A. Morin,Puerto Cabello,1319,2014,70.0,France,3.75,Criollo,Venezuela
9,A. Morin,Pablino,1319,2014,70.0,France,4.00,Unknown,Peru
10,A. Morin,Panama,1011,2013,70.0,France,2.75,Unknown,Panama
11,A. Morin,Madagascar,1011,2013,70.0,France,3.00,Criollo,Madagascar
12,A. Morin,Brazil,1011,2013,70.0,France,3.25,Unknown,Brazil
13,A. Morin,Equateur,1011,2013,70.0,France,3.75,Unknown,Ecuador
14,A. Morin,Colombie,1015,2013,70.0,France,2.75,Unknown,Colombia

### *Data is clean and consistent*

## -

## 3. Save and Export New Cleaned Data

In [37]:
#Export cleaned data
df_cbr.to_csv(os.path.join(path, '02-Data', 'Prepared Data Files', 'flavors_of_cacao_cleaned.csv'))